[JSC] Skip test262 tests fails on Ventura https://bugs.webkit.org/show_bug.cgi?id=275530
Reviewed by Ross Kirsling.

The build bot for test262 on Ventura[1] is failing due to intl402 tests, likely caused by the ICU
version. According to the failure messages[2] from these tests, it seems the lack of support for
'kawi' is the issue. 'kawi' was added in Unicode 15[3], supported from ICU 72[4].

failure messages:
```
FAIL test/intl402/Intl/supportedValuesOf/numberingSystems-with-simple-digit-mappings.js (default)
Full Output:
Exception: Test262Error: kawi with simple digit mappings is supported
FAIL test/intl402/Intl/supportedValuesOf/numberingSystems-with-simple-digit-mappings.js (strict mode)
Full Output:
Exception: Test262Error: kawi with simple digit mappings is supported
FAIL test/intl402/NumberFormat/prototype/format/numbering-systems.js (default)
Full Output:
Exception: Test262Error: numberingSystem: kawi, digit: 0 Expected SameValue(«0», «𑽐») to be true
FAIL test/intl402/NumberFormat/prototype/format/numbering-systems.js (strict mode)
Full Output:
Exception: Test262Error: numberingSystem: kawi, digit: 0 Expected SameValue(«0», «𑽐») to be true
```

This patch updates config.yaml to skip these failing tests.

[1]: https://build.webkit.org/#/builders/1027
[2]: https://build.webkit.org/#/builders/1027/builds/1151
[3]: https://www.unicode.org/versions/Unicode15.0.0/
[4]: https://github.com/unicode-org/icu/releases/tag/release-72-1

* JSTests/test262/config.yaml:

Canonical link: https://commits.webkit.org/280156@main