REGRESSION(r282115): undefined reference to `IPC::messageArgumentDescriptions(IPC::MessageName)' in Debug build https://bugs.webkit.org/show_bug.cgi?id=230064
Unreviewed build fix.

Debug build of non-Cocoa ports were broken since r282115 started
to use IPC::messageArgumentDescriptions for debug logging.
However, MessageArgumentDescriptions.cpp has a long-standing
compilation problem for non-Cocoa ports.

Temporarily disabled the debug logging for non-Cocoa ports by
using ENABLE(IPC_TESTING_API) macro. I'll revert this change after
I will fix the fundamental problem of messages.py.

* Platform/IPC/HandleMessage.h:
(IPC::logMessageImpl):
(IPC::logReply):

Canonical link: https://commits.webkit.org/241469@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@282177 268f45cc-cd09-0410-ab3c-d52691b4dbfc