BUILD FIX: RenderLayerFilterInfo.h needs to include Element.h with ENABLE(SVG)
Fixes the following build failures:

    In file included from Source/WebCore/rendering/RenderLayerFilterInfo.cpp:33:
    Source/WebCore/rendering/RenderLayerFilterInfo.h:118:19: error: use of undeclared identifier 'Element'
        Vector<RefPtr<Element> > m_internalSVGReferences;
                      ^
    Source/WebCore/rendering/RenderLayerFilterInfo.h:118:28: error: expected a type
        Vector<RefPtr<Element> > m_internalSVGReferences;
                               ^
    Source/WebCore/rendering/RenderLayerFilterInfo.h:118:30: error: private field 'm_internalSVGReferences' is not used [-Werror,-Wunused-private-field]
        Vector<RefPtr<Element> > m_internalSVGReferences;
                                 ^
    3 errors generated.

* rendering/RenderLayerFilterInfo.h: Include Element.h within
ENABLE(SVG).  Move ENABLE(SVG) block below unconditional
headers.

Canonical link: https://commits.webkit.org/129624@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@144574 268f45cc-cd09-0410-ab3c-d52691b4dbfc