URTBF after r173659.
After r173659 convertToIntLength() is used only inside ENABLE(DASHBOARD_SUPPORT), so it
became unused function and caused build failure if ENABLE(DASHBOARD_SUPPORT) is false.

Source/WebCore/css/StyleResolver.cpp:1471:15: error: 'WebCore::Length WebCore::convertToIntLength(const WebCore::CSSPrimitiveValue*, const WebCore::CSSToLengthConversionData&)'
defined but not used [-Werror=unused-function] cc1plus: all warnings being treated as errors

* css/StyleResolver.cpp: Missing ENABLE(DASHBOARD_SUPPORT) guard added.

Canonical link: https://commits.webkit.org/154684@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@173660 268f45cc-cd09-0410-ab3c-d52691b4dbfc