Build failure in RemoteFrameClient.h:50:65: error: ‘LayerTreeAsTextOptions’ was not declared in this scope https://bugs.webkit.org/show_bug.cgi?id=282034 rdar://problem/138548450
Unreviewed build fix.

Include missing headers.

* Source/WebCore/page/RemoteFrameClient.h:

Canonical link: https://commits.webkit.org/285643@main