[WinCairo] ImageCairoWin.cpp: error C2660: 'WebCore::BitmapImage::draw': function does not take 6 arguments https://bugs.webkit.org/show_bug.cgi?id=170275
Patch by Fujii Hironori <Hironori.Fujii@sony.com> on 2017-03-30
Reviewed by Said Abou-Hallawa.

Apply the similar change of ImageCGWin.cpp of r214450 to ImageCairoWin.cpp.

* platform/graphics/win/ImageCairoWin.cpp:
(WebCore::BitmapImage::getHBITMAPOfSize): Pass DecodingMode::Synchronous to Image::draw().
(WebCore::BitmapImage::drawFrameMatchingSourceSize): Ditto.

Canonical link: https://commits.webkit.org/187203@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@214606 268f45cc-cd09-0410-ab3c-d52691b4dbfc