[JSC] Make sure WEBASSEMBLY is disabled when JIT is
* follow-up fix for:
  https://bugs.webkit.org/show_bug.cgi?id=242172

* in https://github.com/WebKit/WebKit/commit/a2ec4ef1997d6fafa6ffc607bffb54e76168a918
  #if !CPU(ARM_HARDFP)
  was removed from explit WEBASSEMBLY disabling, so now for
  softfp ARM we can end with JIT disabled and WEBASSEMBLY enabled
  causing build to fail with:
  http://errors.yoctoproject.org/Errors/Details/734587/

In file included from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/js/WebAssemblyFunction.h:32,
                 from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/js/JSWebAssemblyGlobal.h:33,
                 from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/js/JSWebAssemblyInstance.h:31,
                 from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/llint/LLIntOffsetsExtractor.cpp:57:
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmCallee.h: In member function 'std::tuple<void*, void*> JSC::Wasm::JITCallee::rangeImpl() const':
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmCallee.h:95:47: error: invalid use of incomplete type 'class JSC::Compilation'
   95 |         void* start = m_entrypoint.compilation->codeRef().executableMemory()->start().untaggedPtr();
      |                                               ^~
In file included from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmGlobal.h:31,
                 from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/js/JSWebAssemblyGlobal.h:31:
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmFormat.h:49:7: note: forward declaration of 'class JSC::Compilation'
   49 | class Compilation;
      |       ^~~~~~~~~~~
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmCallee.h:96:45: error: invalid use of incomplete type 'class JSC::Compilation'
   96 |         void* end = m_entrypoint.compilation->codeRef().executableMemory()->end().untaggedPtr();
      |                                             ^~
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmFormat.h:49:7: note: forward declaration of 'class JSC::Compilation'
   49 | class Compilation;
      |       ^~~~~~~~~~~
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmCallee.h: In member function 'WTF::CodePtr<(WTF::PtrTag)33222, WTF::FunctionAttributes::None> JSC::Wasm::JITCallee::entrypointImpl() const':
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmCallee.h:100:86: error: invalid use of incomplete type 'class JSC::Compilation'
  100 |     CodePtr<WasmEntryPtrTag> entrypointImpl() const { return m_entrypoint.compilation->code().retagged<WasmEntryPtrTag>(); }
      |                                                                                      ^~
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmFormat.h:49:7: note: forward declaration of 'class JSC::Compilation'
   49 | class Compilation;
      |       ^~~~~~~~~~~
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmCallee.h:100:121: error: expected primary-expression before ')' token
  100 |     CodePtr<WasmEntryPtrTag> entrypointImpl() const { return m_entrypoint.compilation->code().retagged<WasmEntryPtrTag>(); }
      |                                                                                                                         ^
In file included from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/recipe-sysroot/usr/include/c++/13.2.0/memory:78,
                 from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/build/WTF/Headers/wtf/StdLibExtras.h:30,
                 from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/build/WTF/Headers/wtf/FastMalloc.h:26,
                 from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/config.h:39,
                 from TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/llint/LLIntOffsetsExtractor.cpp:26:
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/recipe-sysroot/usr/include/c++/13.2.0/bits/unique_ptr.h: In instantiation of 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = JSC::Compilation]':
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/recipe-sysroot/usr/include/c++/13.2.0/bits/unique_ptr.h:404:17:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = JSC::Compilation; _Dp = std::default_delete<JSC::Compilation>]'
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/webkitgtk-2.40.5/Source/JavaScriptCore/wasm/WasmFormat.h:537:8:   required from here
TOPDIR/tmp-glibc/work/cortexa15t2-vfp-oe-linux-gnueabi/webkitgtk/2.40.5/recipe-sysroot/usr/include/c++/13.2.0/bits/unique_ptr.h:97:23: error: invalid application of 'sizeof' to incomplete type 'JSC::Compilation'
   97 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
ninja: build stopped: subcommand failed.

* explicitly disable WEBASSEMBLY when disabling JIT to avoid this

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>