REGRESSION (r178618): Change to WKWebViewConfiguration broke iOS build <https://bugs.webkit.org/show_bug.cgi?id=140559>
Blind fix to address the following build failure:

    Source/WebKit2/UIProcess/API/Cocoa/WKWebViewConfiguration.mm:79:7: error: interface type cannot be statically allocated
        T m_value;
          ^
          *
    Source/WebKit2/UIProcess/API/Cocoa/WKWebViewConfiguration.mm:94:55: note: in instantiation of template class 'LazyInitialized<WKWebViewContentProviderRegistry>' requested here
        LazyInitialized<WKWebViewContentProviderRegistry> _contentProviderRegistry;
                                                          ^
    Source/WebKit2/UIProcess/API/Cocoa/WKWebViewConfiguration.mm:53:21: error: assigning to 'WKWebViewContentProviderRegistry *' from incompatible type 'RetainPtr<WKWebViewContentProviderRegistry *>'
                m_value = f();
                        ^ ~~~
    Source/WebKit2/UIProcess/API/Cocoa/WKWebViewConfiguration.mm:222:37: note: in instantiation of function template specialization 'LazyInitialized<WKWebViewContentProviderRegistry>::get<(lambda at Source/WebKit2/UIProcess/API/Cocoa/WKWebViewConfiguration.mm:222:41)>' requested here
        return _contentProviderRegistry.get([] { return adoptNS([[WKWebViewContentProviderRegistry alloc] init]); });
                                        ^
    Source/WebKit2/UIProcess/API/Cocoa/WKWebViewConfiguration.mm:57:24: error: property 'get' not found on object of type 'WKWebViewContentProviderRegistry *'
            return m_value.get();
                           ^
    3 errors generated.

* UIProcess/API/Cocoa/WKWebViewConfiguration.mm: Change
_contentProviderRegistry to be a LazyInitialized<RetainPtr<>> to
match other instance variables.

Canonical link: https://commits.webkit.org/158558@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@178625 268f45cc-cd09-0410-ab3c-d52691b4dbfc