Remove SchemeRegistry's list of URL schemes allowing local storage in private browsing, which is unused https://bugs.webkit.org/show_bug.cgi?id=202181
Unreviewed build fix for Windows ports.

..\..\Source\WebKitLegacy\win\WebView.cpp(7342): error C2039: 'registerURLSchemeAsAllowingLocalStorageAccessInPrivateBrowsing': is not a member of 'WebCore::SchemeRegistry'

* WebView.cpp:
(WebView::registerURLSchemeAsAllowingLocalStorageAccessInPrivateBrowsing): Removed calling the removed function.

Canonical link: https://commits.webkit.org/215775@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@250334 268f45cc-cd09-0410-ab3c-d52691b4dbfc