[GTK] Allow using epoll-shim when eventfd is not available. https://bugs.webkit.org/show_bug.cgi?id=253794
Reviewed by NOBODY (OOPS!).

OpenBSD does not have eventfd(2) but instead relies on an external
implementation (library) called epoll-shim.
epoll-shim already comes with it's "read" definition which clashes with WebKit:
webkitgtk40-2.39.91/webkitgtk-2.39.91/Source/WebCore/platform/graphics/iso/ISOBox.h:71:33: error: no member named 'read' in 'JSC::DataView'

Using @no-unify prevents tainting the rest of the unified code and allows the
build to succeed.

* Source/WebCore/SourcesGTK.txt: