Cherry-pick r269071. rdar://problem/70831166
    Web Inspector: REGRESSION(r266669): Uncaught Exception: TypeError: node.nodeType is not a function. (In 'node.nodeType()', 'node.nodeType' is undefined)
    https://bugs.webkit.org/show_bug.cgi?id=218254

    Reviewed by Joseph Pecoraro.

    r266669 changed `WI.DOMBreakpoint` to use `WI.DOMNode` instead of `DOM.NodeId`, meaning that
    `WI.DOMTreeContentView.prototype._updateBreakpointStatus` now expects a `WI.DOMNode`.

    * UserInterface/Views/DOMTreeContentView.js:
    (WI.DOMTreeContentView.prototype._domTreeElementAdded):

    Canonical link: https://commits.webkit.org/230959@main
    git-svn-id: https://svn.webkit.org/repository/webkit/trunk@269071 268f45cc-cd09-0410-ab3c-d52691b4dbfc

Canonical link: https://commits.webkit.org/230609.27@safari-611.1.4-branch
git-svn-id: https://svn.webkit.org/repository/webkit/branches/safari-611.1.4-branch@269194 268f45cc-cd09-0410-ab3c-d52691b4dbfc