Unused lambda in JSWebKitSubtleCrypto::wrapKey() <https://webkit.org/b/172087>
Reviewed by Chris Dumez.

Fixes the following warning with newer clang:

    Source/WebCore/bindings/js/JSWebKitSubtleCryptoCustom.cpp:594:35: error: lambda capture 'keyFormat' is not used [-Werror,-Wunused-lambda-capture]
        auto exportSuccessCallback = [keyFormat, algorithm, parameters, wrappingKey, wrapper](const Vector<uint8_t>& exportedKeyData) mutable {
                                      ^

* bindings/js/JSWebKitSubtleCryptoCustom.cpp:
(WebCore::JSWebKitSubtleCrypto::wrapKey): Remove unused lambda.


Canonical link: https://commits.webkit.org/189023@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@216838 268f45cc-cd09-0410-ab3c-d52691b4dbfc