Fix build on non-Linux platforms https://bugs.webkit.org/show_bug.cgi?id=285806
Reviewed by NOBODY (OOPS!).

m_resourceUsageOverlay is only defined when RESOURCE_USAGE is enabled:

   -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-gnu/dbus-1.0/include -fdiagnostics-color=always -Wextra -Wall -pipe -fmax-errors=20 -Wno-odr -Wno-stringop-overread -Wno-stringop-overflow -Wno-nonnull -Wno-array-bounds -Wno-expansion-to-defined -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-maybe-uninitialized -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare -fasynchronous-unwind-tables -g1 -O2 -ffile-prefix-map=/build/webkit2gtk-2.48.0=. -fstack-protector-strong -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -DNDEBUG -DG_DISABLE_CAST_CHECKS -fno-strict-aliasing -fno-exceptions -fno-rtti -fcoroutines -ffunction-sections -fdata-sections -std=c++23 -fPIC -fvisibility=hidden -pthread -DHWY_SHARED_DEFINE -DAVIF_DLL -DEB_DLL -DHAVE_HB_FEATURES_H -MD -MT Source/WebCore/CMakeFiles/WebCore.dir/__/__/WebCore/DerivedSources/unified-sources/UnifiedSource-767013ce-8.cpp.o -MF Source/WebCore/CMakeFiles/WebCore.dir/__/__/WebCore/DerivedSources/unified-sources/UnifiedSource-767013ce-8.cpp.o.d -o Source/WebCore/CMakeFiles/WebCore.dir/__/__/WebCore/DerivedSources/unified-sources/UnifiedSource-767013ce-8.cpp.o -c /build/webkit2gtk-2.48.0/build-soup3/WebCore/DerivedSources/unified-sources/UnifiedSource-767013ce-8.cpp
In file included from /build/webkit2gtk-2.48.0/build-soup3/WebCore/DerivedSources/unified-sources/UnifiedSource-767013ce-8.cpp:4:
/build/webkit2gtk-2.48.0/Source/WebCore/page/Page.cpp: In destructor ‘WebCore::Page::~Page()’:
/build/webkit2gtk-2.48.0/Source/WebCore/page/Page.cpp:542:39: error: ‘m_resourceUsageOverlay’ was not declared in this scope; did you mean ‘resourceUsageOverlay’?
  542 |     if (RefPtr resourceUsageOverlay = m_resourceUsageOverlay)
      |                                       ^~~~~~~~~~~~~~~~~~~~~~
      |                                       resourceUsageOverlay

* Source/WebCore/page/Page.cpp:
(WebCore::Page::~Page):