REGRESSION(269270@main): [Win] FontCairo.cpp: error: no member named 'uncheckedAppend' in 'WTF::Vector<cairo_glyph_t>' https://bugs.webkit.org/show_bug.cgi?id=215259
Unreviewed build fix.

* Source/WebCore/platform/graphics/cairo/FontCairo.cpp:
Use append instead of uncheckedAppend.

Canonical link: https://commits.webkit.org/269275@main