Web Inspector: REGRESSION (r269359): Timelines: TypeError: this.deselect is not a function https://bugs.webkit.org/show_bug.cgi?id=223698 <rdar://problem/75790983>
Reviewed by BJ Burg.

Ensure individual timeline views can be closed to return to the Timelines overview.

* UserInterface/Views/TimelineTreeElement.js:
(WI.TimelineTreeElement.prototype._showCloseButton):


Canonical link: https://commits.webkit.org/235713@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@274960 268f45cc-cd09-0410-ab3c-d52691b4dbfc