REGRESSION(284255@main): Unreviewed build fix https://bugs.webkit.org/show_bug.cgi?id=280377
> parser/CSSPropertyParserConsumer+ColorInterpolationMethod.h(37,101): error: unknown type name 'CSSParserContext'

* Source/WebCore/css/parser/CSSPropertyParserConsumer+ColorInterpolationMethod.h: