REGRESSION(279720@main): [webkitscmpy] conflicting subparser: clean https://bugs.webkit.org/show_bug.cgi?id=275137
Reviewed by Jonathan Bedard.

After https://commits.webkit.org/279720@main, WPE and WinCairo buildbots were failing.

> Traceback (most recent call last):
>   File "/home/buildbot/worker/WPE-Linux-64-bit-Release-Build/build/Tools/Scripts/git-webkit", line 63, in <module>
>     sys.exit(program.main(
>              ^^^^^^^^^^^^^
>   File "/home/buildbot/worker/WPE-Linux-64-bit-Release-Build/build/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/__init__.py", line 117, in main
>     subparser = subparsers.add_parser(program.name, **kwargs)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/argparse.py", line 1197, in add_parser
>     raise ArgumentError(self, _('conflicting subparser: %s') % name)
> argparse.ArgumentError: argument {help,blame,branch,canonicalize,checkout,clean,clone,find,list,info,land,log,pull,up,update,pull-request,pr,pfr,upload,revert,review,setup,install-git-lfs}: conflicting subparser: clean

* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/__init__.py:
Removed duplicated programs.

Canonical link: https://commits.webkit.org/279723@main