2010-01-05  Adam Barth  <abarth@webkit.org>
        Reviewed by Darin Adler.

        Fix obscure queue crash in queueengine
        https://bugs.webkit.org/show_bug.cgi?id=33196

        Sometimes we get an exception that can't be stringified.  For example:

        AttributeError: 'ParseError' object has no attribute 'msg'

        In these cases, the whole queue dies because we're in the global
        exception handler.  Instead of dieing here, we should just print a less
        informative message to the console.  We're already printing the whole
        backtrace anyway, so there's not much point to stringifying the
        exception anyway.

        * Scripts/webkitpy/queueengine.py:

Canonical link: https://commits.webkit.org/44226@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@52814 268f45cc-cd09-0410-ab3c-d52691b4dbfc