jsc.exe is unable to dump exception output to a file https://bugs.webkit.org/show_bug.cgi?id=254799
Reviewed by Keith Miller.

Currently, Win JSC fails various ChakraCore tests due to diff failures.

The crux of the issue is that this works:
```
> .\WebKitBuild\Debug\bin64\jsc.exe .\JSTests\ChakraCore\test\jsc-lib.js .\JSTests\ChakraCore\test\Basics\bug650104.js
name: push -2885562136746910000number
undefined
Exception: TypeError: Number().push is not a function. (In 'Number().push()', 'Number().push' is undefined)
global code@.\JSTests\ChakraCore\test\Basics\bug650104.js:18:14
```
But if we add `> out.txt` to the end, the file contains just the first two lines and lacks the dumped exception.

The fix is simply to flush before exiting.

* Source/JavaScriptCore/jsc.cpp:
(dumpException):

Canonical link: https://commits.webkit.org/262402@main