MSVC reports "wtf/RetainPtr.h(196): error C3861: 'CFAutorelease': identifier not found " with /permissive- on Windows https://bugs.webkit.org/show_bug.cgi?id=202842
Reviewed by Darin Adler.

r287200 fixed the problem, but not a right fix.

* wtf/PlatformHave.h: Defined a new macro HAVE_CFAUTORELEASE for PLATFORM(COCOA).
* wtf/RetainPtr.h: Use HAVE(CFAUTORELEASE) instead of PLATFORM(COCOA).



Canonical link: https://commits.webkit.org/245421@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@287265 268f45cc-cd09-0410-ab3c-d52691b4dbfc