[CMake] Declare WebCore-migrated headers textual in WebKitLegacy private modulemap on iOS https://bugs.webkit.org/show_bug.cgi?id=315574 rdar://177959268
Reviewed by NOBODY (OOPS!).

The cmake-generated WebKitLegacy.framework/Modules/module.private.modulemap
listed every staged header as `header`, including the WebCore-migrated set
(WAKView.h, WebEvent.h, WebCoreThread.h, ...). WebCore_Private.Core
already owns those @interfaces, so under -explicit-module-build the
WebKitLegacy PCM compile failed with:

  WebFrameView.h:45:27: error: definition of 'WAKView' must be imported
  from module 'WebCore_Private.Core.WAKView' before it is required

Emit the migrated headers as `textual header` so WebKitLegacy stops
claiming ownership. The staged copies remain reachable via
`<WebKitLegacy/X.h>`.

* Source/WebKitLegacy/PlatformIOS.cmake: