Cherry-pick 321373@main (271772f23f69). https://bugs.webkit.org/show_bug.cgi?id=324525
    [WebKit][GLIB] Fix missing include in WebKitDownload

    https://bugs.webkit.org/show_bug.cgi?id=324525

    Reviewed by Claudio Saavedra.

    /home/thomas/Documents/nd_falcon_rebase/buildroot-mna240/output/build/webkitgtk-2.54.0/Source/WebKit/UIProcess/API/glib/WebKitDownload.cpp:534:33: error: ‘CStringView’ has not been declared
      534 |     auto isFileURI = startsWith(CStringView::unsafeFromUTF8(destination).span(), "file://"_s);
          |                                 ^~~~~~~~~~~

    Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>
    Canonical link: https://commits.webkit.org/321373@main

Canonical link: https://commits.webkit.org/317695.339@webkitglib/2.54