BUILD FIX: FormController.cpp fails to build on 32-bit architectures
This fixes the following build failure introduced in r121004 for
Bug 89628:

    FormController.cpp:62:36: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Werror,-Wshorten-64-to-32]
        state.m_values.reserveCapacity(valueSize);
        ~~~~~                          ^~~~~~~~~

* html/FormController.cpp:
(WebCore::FormControlState::deserialize): Change type of
valueSize from uint64_t to size_t.

Canonical link: https://commits.webkit.org/107615@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@121032 268f45cc-cd09-0410-ab3c-d52691b4dbfc