git-webkit install-hooks is failing - AttributeError: 'IdentifierTrailer' object has no attribute 'split' https://bugs.webkit.org/show_bug.cgi?id=321968 rdar://185152046
Unreviewed infrastructure fix.

This regressed in 319313@main (761e61f4ad96), from bug 316952.

We didn't udpate webkitscmpy.program.install_hooks for the change of
API, and we don't have Python type checking to have caught this.

* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/install_hooks.py:
(InstallHooks.main):
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/test/install_hooks_unittest.py:
(TestInstallHooks.write_hook):
(TestInstallHooks.test_install_hook_with_identifier_trailer):

Canonical link: https://commits.webkit.org/319316@main