mod_pywebsocket: module 'ssl' has no attribute 'wrap_socket' with Python 3.12 https://bugs.webkit.org/show_bug.cgi?id=280224
Reviewed by NOBODY (OOPS!).

run-webkit-tests was failing to start the WebSocket server with Python
3.12 due to an error in pywebsocket3/mod_pywebsocket/websocket_server.py.
> AttributeError: module 'ssl' has no attribute 'wrap_socket'

<https://github.com/web-platform-tests/wpt/commit/a7a594d8c03a850fd99bab1fd85bb6fe310081a2>
moved mod_pywebsocket/standalone.py to pywebsocket3/standalone.py.
> rename tools/third_party/pywebsocket3/{mod_pywebsocket => pywebsocket3}/standalone.py (96%)
Then, <https://github.com/web-platform-tests/wpt/commit/efa4a99b8dde1d9ab572efb9e1757e6900289bed>
fixed the problem for the new one.

Switched run-webkit-tests to execute the new one.

I'll rerun import-w3c-tests with --clean-dest-dir switch to remove the
old mod_pywebsocket directory in a follow-up patch.

With the above change,
http/tests/websocket/tests/hybi/handshake-ok-with-http-version-beyond-1_1.html
failed with an error message "Compressed bit must be 0 if no
negotiated deflate-frame extension". Send a close frame as well as
<https://github.com/web-platform-tests/wpt/blob/master/websockets/handlers/simple_handshake_wsh.py>.

* LayoutTests/http/tests/websocket/tests/hybi/handshake-ok-with-http-version-beyond-1_1_wsh.py:
(web_socket_do_extra_handshake):
* Tools/Scripts/webkitpy/layout_tests/servers/websocket_server.py:
(PyWebSocket._prepare_config):