cmake build fix: PAL is missing WebContentAnalysisSoftLink.h from PAL_PUBLIC_HEADERS https://bugs.webkit.org/show_bug.cgi?id=324901 rdar://188130360
Reviewed by Zak Ridouh.

301882@main added pal/cocoa/WebContentAnalysisSoftLink.h and registered it in
PAL.xcodeproj, but not in PAL_PUBLIC_HEADERS. cmake therefore never stages it
into PAL/Headers/pal/cocoa/, and any cmake build which includes it fails:

    Tools/TestWebKitAPI/Tests/IPC/IPCSerialization.mm:61:9: fatal error:
        'pal/cocoa/WebContentAnalysisSoftLink.h' file not found

* Source/WebCore/PAL/pal/PlatformCocoa.cmake:

Canonical link: https://commits.webkit.org/321655@main