REGRESSION (r194470): Fix warnings uncovered by migrating to WTF_MOVE <https://bugs.webkit.org/show_bug.cgi?id=152601>
Ignore unknown pragmas on older clangs.  Fixes the following
build failure:

    Tools/TestWebKitAPI/Tests/WTF/NakedPtr.cpp:184:34: error: unknown warning group '-Wself-move', ignored [-Werror,-Wunknown-pragmas]
    #pragma clang diagnostic ignored "-Wself-move"
                                     ^
    1 error generated.

* TestWebKitAPI/Tests/WTF/NakedPtr.cpp:
(TestWebKitAPI::TEST):
* TestWebKitAPI/Tests/WTF/RefPtr.cpp:
(TestWebKitAPI::TEST):

Canonical link: https://commits.webkit.org/170711@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@194473 268f45cc-cd09-0410-ab3c-d52691b4dbfc