Add Federico Bucchi to list of WebKit contributors https://bugs.webkit.org/show_bug.cgi?id=218136
- Added Federico Bucchi
- Removed "slackId" : "UTWC5TTSP", because it was causing:
ERROR: Tools/Scripts/webkitpy/common/config/contributors.json:0:  contributors.json differs from the canonical format.

Patch by Federico Bucchi <fbucchi@apple.com> on 2020-10-26
Reviewed by Brian Burg.

* Scripts/webkitpy/common/config/contributors.json:

Canonical link: https://commits.webkit.org/230905@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@269002 268f45cc-cd09-0410-ab3c-d52691b4dbfc