Unreviewed, reverting 281279@main. https://bugs.webkit.org/show_bug.cgi?id=276994
Broke wincairo build (follow-up)

Reverted changeset:

"REGRESSION(281277@main): wasm/WasmMemory.h:112:5: error: no template named 'WeakGCSet'"
https://bugs.webkit.org/show_bug.cgi?id=276963
https://commits.webkit.org/281279@main

Canonical link: https://commits.webkit.org/281289@main