REGRESSION (r183293): Fix iOS EWS build by adding SPI declaration for +[UIPeripheralHost visiblePeripheralFrame]
Fixes the following build failures:

    WebKit2/UIProcess/ios/WKPDFView.mm:740:45: error: class method '+visiblePeripheralFrame' not found (return type defaults to 'id') [-Werror,-Wobjc-method-access]
        CGRect keyboardRect = [UIPeripheralHost visiblePeripheralFrame];
                                                ^~~~~~~~~~~~~~~~~~~~~~
    WebKit2/UIProcess/ios/WKPDFView.mm:740:12: error: no viable conversion from 'id' to 'CGRect'
        CGRect keyboardRect = [UIPeripheralHost visiblePeripheralFrame];
               ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Platform/spi/ios/UIKitSPI.h:
(+[UIPeripheralHost visiblePeripheralFrame]): Add declaration.

Canonical link: https://commits.webkit.org/162162@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@183296 268f45cc-cd09-0410-ab3c-d52691b4dbfc