[GTK] fix USE_EGL checks when GBM renderer is used
https://bugs.webkit.org/show_bug.cgi?id=262169

Reviewed by Michael Catanzaro.

Regression since commit 81c064ddb4182a34a36def401025d223ca0d31ba.

webkitgtk-2.42.0/Source/WebKit/UIProcess/gtk/AcceleratedBackingStoreDMABuf.cpp:39:10: fatal error: epoxy/egl.h: No such file or directory
   39 | #include <epoxy/egl.h>
      |          ^~~~~~~~~~~~~

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>
Canonical link: https://commits.webkit.org/266719.76@bugfix/USE_EGL-2.42