Web Inspector: Exception: TypeError: undefined is not a function (evaluating 'marker.find()') https://bugs.webkit.org/show_bug.cgi?id=125724
Patch by Joseph Pecoraro <pecoraro@apple.com> on 2013-12-13
Reviewed by Darin Adler.

* UserInterface/CSSStyleDeclarationTextEditor.js:
(WebInspector.CSSStyleDeclarationTextEditor.prototype.):
(WebInspector.CSSStyleDeclarationTextEditor.prototype._createColorSwatches):
The callback changed to returning WebInspector.TextMarkers, however
this class expected a raw CodeMirror marker. Since this class knows
about CodeMirror and expects to access these markers later go
directly to the CodeMirror marker.

Canonical link: https://commits.webkit.org/143753@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@160585 268f45cc-cd09-0410-ab3c-d52691b4dbfc