JavaScriptCore: forward MacroAssemblerRISCV64.h and friends to PrivateHeaders https://bugs.webkit.org/show_bug.cgi?id=315509
Reviewed by NOBODY (OOPS!).

JSC's CMakeLists copies a curated list of assembler headers into
PrivateHeaders/JavaScriptCore/ so that external consumers (WebCore,
WebKit, JSC's own GLib bindings, ...) can resolve them via
'#include <JavaScriptCore/MacroAssembler.h>'. That header in turn
does '#include "MacroAssemblerRISCV64.h"' on RISCV64, which in turn
does '#include "RISCV64Assembler.h"', which in turn pulls in
RISCV64Registers.h. None of the three is in the forwarding list.

MacroAssemblerARM64.h / MacroAssemblerARMv7.h / MacroAssemblerX86_64.h
are listed alongside their respective ARM64Assembler.h / ARM64Registers.h
/ X86Assembler.h / X86_64Registers.h; the RISCV64 trio simply hadn't
been added.  As a result, on RISCV64 every WebCore translation unit
that pulls in JSC's MacroAssembler chain fails with:

  MacroAssembler.h:54:10: fatal error: MacroAssemblerRISCV64.h:
                                       No such file or directory

or

  MacroAssemblerRISCV64.h:33:10: fatal error: RISCV64Assembler.h:
                                              No such file or directory

Add the three RISCV64 headers to the forwarding-headers list, matching
what is already done for the other architectures.

Signed-off-by: Daniel Golle <daniel@makrotopia.org>