REGRESSION(262723@main) Unreviewed build fix for non-Cocoa ports https://bugs.webkit.org/show_bug.cgi?id=255163
> WebProcess/FullScreen/WebFullScreenManager.cpp(32): fatal error C1083: Cannot open include file: 'VideoFullscreenManager.h': No such file or directory

* Source/WebKit/WebProcess/FullScreen/WebFullScreenManager.cpp:
Include VideoFullscreenManager.h only if needed.