REGRESSION(281277@main): wasm/WasmMemory.h:112:5: error: no template named 'WeakGCSet' https://bugs.webkit.org/show_bug.cgi?id=276963
Unreviewed build fix for PlayStation and Windows ports.

* Source/JavaScriptCore/wasm/WasmMemory.h:
Added a missing #include "WeakGCSet.h".

Canonical link: https://commits.webkit.org/281279@main