Unreviewed build fix after r158984.
No needs to include "KeyedEncoder.h".
WebKit/Source/WebKit2/WebProcess/WebPage/WebBackForwardListProxy.cpp:31:26: fatal error: KeyedEncoder.h: No such file or directory

* WebProcess/WebPage/WebBackForwardListProxy.cpp: Removed #include line.

Canonical link: https://commits.webkit.org/142287@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@158990 268f45cc-cd09-0410-ab3c-d52691b4dbfc