REGRESSION(279061@main): [clang 18] error: 'suppress' attribute only applies to variables and statements https://bugs.webkit.org/show_bug.cgi?id=274484
Reviewed by Ryosuke Niwa.

After 279061@main introduced SUPPRESS_UNCOUNTED_MEMBER and
SUPPRESS_REFCOUNTED_WITHOUT_VIRTUAL_DESTRUCTOR, Windows port couldn't
compile with clang-cl 18.

> UniquedStringImpl.h(34,7): error: 'suppress' attribute only applies to variables and statements
> StringConcatenate.h(266,5): error: 'suppress' attribute only applies to variables and statements

Clang 18 support 'suppress' attributes, but it can be applied only to
variables and statements.

Introduced IGNORE_CLANG_19_STATIC_ANALYZER_WARNINGS_ATTRIBUTE() macro
which works samely with IGNORE_CLANG_STATIC_ANALYZER_WARNINGS_ATTRIBUTE
only for Apple Clang and Clang>=19.

* Source/WTF/wtf/Compiler.h:

Canonical link: https://commits.webkit.org/279094@main