2010-11-16  Kenneth Russell  <kbr@google.com>
        Reviewed by Dimitri Glazkov.

        WebIDL conversions from string to number and array to number should not generate TypeError
        https://bugs.webkit.org/show_bug.cgi?id=49218

        Recent SVG-related changes to the StrictTypeChecking extended attribute in
        CodeGeneratorJS.pm and CodeGeneratorV8.pm were not correct according to the Web IDL and
        ECMA-262 specifications. In particular, when an attribute or function argument is specified
        as a number type (floating-point or integer), passing in a String or object is not supposed
        to raise an exception.

        The original intent of the StrictTypeChecking extended attribute was to properly raise
        TypeError when an interface type is required, but the supplied object does not implement the
        interface type (http://dev.w3.org/2006/webapi/WebIDL/#es-interface). Historically WebKit has
        silently passed null to the C++ bindings in this case. The handling of strings in the
        original StrictTypeChecking implementation was also incorrect, raising exceptions when it
        should not.

        The semantics of StrictTypeChecking have been changed to enforce only the restrictions on
        interface types. The V8 custom bindings for WebGL have been updated to match the behavior of
        the autogenerated code.

        Test: fast/canvas/webgl/type-conversion-test.html

        * bindings/scripts/CodeGeneratorJS.pm:
        * bindings/scripts/CodeGeneratorV8.pm:
        * bindings/v8/custom/V8WebGLRenderingContextCustom.cpp:
        (WebCore::getObjectParameter):
        (WebCore::V8WebGLRenderingContext::getFramebufferAttachmentParameterCallback):
        (WebCore::V8WebGLRenderingContext::getParameterCallback):
        (WebCore::V8WebGLRenderingContext::getProgramParameterCallback):
        (WebCore::V8WebGLRenderingContext::getShaderParameterCallback):
        (WebCore::vertexAttribAndUniformHelperf):
2010-11-16  Kenneth Russell  <kbr@google.com>

        Reviewed by Dimitri Glazkov.

        WebIDL conversions from string to number and array to number should not generate TypeError
        https://bugs.webkit.org/show_bug.cgi?id=49218

        Updated SVG tests which were incorrectly expecting exceptions to be raised when the Web IDL
        and ECMA-262 specifications state that none should be. Incorporated WebGL test from Khronos
        repository verifying the passing objects of various types to APIs.

        Ran all layout tests in Safari on Mac OS X.

        * fast/canvas/webgl/type-conversion-test-expected.txt: Added.
        * fast/canvas/webgl/type-conversion-test.html: Added.
        * svg/dom/SVGAngle-expected.txt:
        * svg/dom/SVGAnimatedBoolean-expected.txt:
        * svg/dom/SVGAnimatedEnumeration-expected.txt:
        * svg/dom/SVGAnimatedInteger-expected.txt:
        * svg/dom/SVGAnimatedNumber-expected.txt:
        * svg/dom/SVGLength-expected.txt:
        * svg/dom/SVGMatrix-expected.txt:
        * svg/dom/SVGNumber-expected.txt:
        * svg/dom/SVGPoint-expected.txt:
        * svg/dom/SVGPreserveAspectRatio-expected.txt:
        * svg/dom/SVGRect-expected.txt:
        * svg/dom/SVGTransform-expected.txt:
        * svg/dom/script-tests/SVGAngle.js:
        * svg/dom/script-tests/SVGAnimatedBoolean.js:
        * svg/dom/script-tests/SVGAnimatedEnumeration.js:
        * svg/dom/script-tests/SVGAnimatedInteger.js:
        * svg/dom/script-tests/SVGAnimatedNumber.js:
        * svg/dom/script-tests/SVGLength.js:
        * svg/dom/script-tests/SVGMatrix.js:
        * svg/dom/script-tests/SVGNumber.js:
        * svg/dom/script-tests/SVGPoint.js:
        * svg/dom/script-tests/SVGPreserveAspectRatio.js:
        * svg/dom/script-tests/SVGRect.js:
        * svg/dom/script-tests/SVGTransform.js:


Canonical link: https://commits.webkit.org/62591@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@72123 268f45cc-cd09-0410-ab3c-d52691b4dbfc