[chromium] Remove unused variable (gcc 4.6 complains about this) https://bugs.webkit.org/show_bug.cgi?id=73335
../../third_party/WebKit/Source/WebCore/platform/graphics/chromium/cc/CCDamageTracker.cpp:296:19:
error: variable 'oldReplicaMaskRect' set but not used [-Werror=unused-but-set-variable]

* platform/graphics/chromium/cc/CCDamageTracker.cpp:
(WebCore::CCDamageTracker::extendDamageForRenderSurface):

Canonical link: https://commits.webkit.org/89879@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@101398 268f45cc-cd09-0410-ab3c-d52691b4dbfc