REGRESSION (r180260): Try to fix incremental builds by changing UserContentController.cpp
Attempt to fix this linker error by making a non-coding change:

    Undefined symbols for architecture i386:
      "__ZN7WebCore17ContentExtensions24ContentExtensionsBackendC1Ev", referenced from:
          __ZN7WebCore21UserContentController20addUserContentFilterERKN3WTF6StringES4_ in UserContentController.o
    ld: symbol(s) not found for architecture i386

This should have been fixed by r180266, but perhaps Xcode didn't
recognize that it needed to rebuild this source file.

* page/UserContentController.cpp: Update copyright.

Canonical link: https://commits.webkit.org/159770@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@180269 268f45cc-cd09-0410-ab3c-d52691b4dbfc