Add missing journald include for WTF https://bugs.webkit.org/show_bug.cgi?id=254495
Reviewed by NOBODY (OOPS!).

This fixes the following compilation error:

   /tmp/guix-build-webkitgtk-2.40.0.drv-0/build/WTF/Headers/wtf/Assertions.h:56:10: fatal error: systemd/sd-journal.h: No such file or directory
      56 | #include <systemd/sd-journal.h>
         |          ^~~~~~~~~~~~~~~~~~~~~~

* Source/WTF/wtf/CMakeLists.txt: Add JOURNALD_INCLUDE_DIR to
WTF_INTERFACE_INCLUDE_DIRECTORIES.