REGRESSION(260407@main) Unreviewed build fix for Windows port https://bugs.webkit.org/show_bug.cgi?id=252279
Patch by Alan Baradlay

Windows port couldn't compile.

> layout/formattingContexts/inline/invalidation/InlineInvalidation.cpp(62): error C3487: 'unsigned long': all return expressions must deduce to the same type: previously it was 'size_t'
> layout/formattingContexts/inline/invalidation/InlineInvalidation.cpp(61): error C3487: 'unsigned long': all return expressions must deduce to the same type: previously it was 'size_t'

* Source/WebCore/layout/formattingContexts/inline/invalidation/InlineInvalidation.cpp:
(WebCore::Layout::InlineInvalidation::textInserted):

Canonical link: https://commits.webkit.org/260421@main