REGRESSION(319506@main): HAVE(APPKIT_GESTURES_SUPPORT) build is broken ('AppKitGesturesTests.RefreshControl' does not conform to protocol 'AppKitGestureTestSuite') https://bugs.webkit.org/show_bug.cgi?id=322169 rdar://185399358
Unreviewed build fix.

This patch addresses the following build error:

```
/Tools/TestWebKitAPI/Tests/WebKit/WebPage/AppKit Gesture Tests/RefreshControlGesturesTests.swift:38:17: error: type 'AppKitGesturesTests.RefreshControl' does not conform to protocol 'AppKitGestureTestSuite'
    final class RefreshControl: AppKitGestureTestSuite {
/Tools/TestWebKitAPI/Tests/WebKit/WebPage/AppKit Gesture Tests/RefreshControlGesturesTests.swift:38:17: note: add stubs for conformance
    final class RefreshControl: AppKitGestureTestSuite {
/Tools/TestWebKitAPI/Tests/WebKit/WebPage/AppKit Gesture Tests/AppKitGesturesTestsSupport.swift:78:16: note: protocol requires property 'text' with type 'String'
    static var text: String { get }
```

I regrettably dropped the `static var text` value from the RefreshControl
class, which meant it no longer conformed to the AppKitGestureTestSuite
protocol. We fix the issue in this patch.

* Tools/TestWebKitAPI/Tests/WebKit/WebPage/AppKit Gesture Tests/RefreshControlGesturesTests.swift:

Canonical link: https://commits.webkit.org/319517@main