Web Inspector: Uncaught Exception opening Web Inspector - TypeError: undefined is not a function - candidateObjectCookie.every https://bugs.webkit.org/show_bug.cgi?id=135762
Patch by Joseph Pecoraro <pecoraro@apple.com> on 2014-08-08
Reviewed by Timothy Hatcher.

* UserInterface/Views/NavigationSidebarPanel.js:
(WebInspector.NavigationSidebarPanel.prototype.treeElementMatchesCookie):
Fix a typo, the wrong object was being used.

Canonical link: https://commits.webkit.org/153639@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@172350 268f45cc-cd09-0410-ab3c-d52691b4dbfc