Fix iOS 16 build error in TestWKWebView
Unreviewed build fix.

Add missing conformance to _UITextSearching to TestWKWebKiew. Fixes
open-source-only build errors like:

  error: 'TestWKWebView' may not respond to 'didBeginTextSearchOperation' [-Werror]
  error: 'TestWKWebView' may not respond to 'didEndTextSearchOperation' [-Werror]
  error: 'TestWKWebView' may not respond to 'didBeginTextSearchOperation' [-Werror]

* Tools/TestWebKitAPI/Tests/WebKitCocoa/FindInPage.mm:

Canonical link: https://commits.webkit.org/254499@main