REGRESSION(273951@main): Unreviewed build fix for Windows port
> WebProcess\GPU\graphics\RemoteImageBufferProxy.h(65,28): error: no type named 'Connection' in namespace 'IPC'; did you mean 'Condition'?

* Source/WebKit/WebProcess/GPU/graphics/RemoteImageBufferProxy.h:
Added a forward declaration of IPC::Connection.

Canonical link: https://commits.webkit.org/273969@main