[JSC] Fix build break since r202502 - 2 https://bugs.webkit.org/show_bug.cgi?id=159194
Reviewed by Gyuyoung Kim.

Fix about the error message below.
error: control reaches end of non-void function [-Werror=return-type]

* b3/B3TypeMap.h: add #pragma GCC diagnostic ignored "-Wreturn-type".


Canonical link: https://commits.webkit.org/177302@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@202555 268f45cc-cd09-0410-ab3c-d52691b4dbfc