[GCC] Unreviewed, build fix Debian 11 after 278696@main https://bugs.webkit.org/show_bug.cgi?id=245970
error: expected ‘(’ before ‘{’ token.

In GCC10.2, lambda with no arguments requires parenthesis.

* Source/WebCore/css/parser/CSSPropertyParserConsumer+Color.cpp:
(WebCore::CSSPropertyParserHelpers::consumeColorFunction):

Canonical link: https://commits.webkit.org/278766@main