<http://webkit.org/b/28367> bugzilla.py: replace ScriptError class with BugzillaError class
        Reviewed by David Levin.

        The ScriptError class doesn't exist in bugzilla.py, so any
        errors print error messages about ScriptError instead of the
        actual error:

            NameError: global name 'ScriptError' is not defined

        * Scripts/modules/bugzilla.py:
        (BugzillaError): Added class.  Modeled after ScriptError class
        in scm.py.
        (Bugzilla.authenticate): Changed to use BugzillaError instead of
        ScriptError.
        (Bugzilla._check_create_bug_response): Ditto.

Canonical link: https://commits.webkit.org/38945@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@47344 268f45cc-cd09-0410-ab3c-d52691b4dbfc