[cmake] Rearrange WebCore module path https://bugs.webkit.org/show_bug.cgi?id=319039 rdar://181886273
Reviewed by NOBODY (OOPS!).

This reverts the modulemap path for WebCore back to the
situation before https://commits.webkit.org/314398@main.
This is necessary to solve problems like:

WebCore/DiagnosticLoggingClient.h:49:5: error: 'WebCore::DiagnosticLoggingClient'
has different definitions in different modules; first difference is
definition in module 'WebKit_Internal.WebPageCreationParameters' found method
'operator new' with body

This is a partial revert of https://commits.webkit.org/314398@main
which retains the cross-platform nature of the modulemap added there,
but sets everything else back to the way it was before.

The reason for the unexpected behavior change for Mac builds is believed
to be that some consumers did not have the -I flag to respect the
SwiftModules/WebCorePrivate modulemap directory that was added. So,
instead of respecting the modulemap there, they instead used the
modulemap found alongside the source code. This resulted in
cnflciting definitions for WebCore types. This partial revert moves
the mini WebCore modulemap back to the directory which all consumers
search; they'll all use that.

It is still desirable that the cmake build eventually switches to using
the same full WebCore modulemap that the Xcode build uses. For now,
this unbreaks the build.