REGRESSION (r257472): Can't start old Safari with new WebKit (dyld: Symbol not found: _WKContextConfigurationSetShouldCaptureAudioInUIProcess) https://bugs.webkit.org/show_bug.cgi?id=209155
Reviewed by Eric Carlson.

Add a no-op WKContextConfigurationSetShouldCaptureAudioInUIProcess to allow latest WebKit being run on older Safari.

* UIProcess/API/C/WKContextConfigurationRef.cpp:
(WKContextConfigurationSetShouldCaptureAudioInUIProcess):
* UIProcess/API/C/WKContextConfigurationRef.h:


Canonical link: https://commits.webkit.org/222142@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@258629 268f45cc-cd09-0410-ab3c-d52691b4dbfc