REGRESSION(284780@main): [GTK][WPE][Debug] Fix the build https://bugs.webkit.org/show_bug.cgi?id=281051
Reviewed by NOBODY (OOPS!).

GCC doesn't seem to like that we are trying to compare a bitfield and an enum class.

/app/webkit/Source/WebCore/rendering/RenderLayer.cpp:1272:37: error: no match for ‘operator==’ (operand types are ‘unsigned char:2’ and ‘WebCore::RepaintStatus’)
 1272 |         LAYER_POSITIONS_ASSERT(dest == source);

* Source/WebCore/rendering/RenderLayer.h: