cmake builds broken due to mismatched types in Opus Silk (Third-Party) https://bugs.webkit.org/show_bug.cgi?id=325734 rdar://188760754
Reviewed by Youenn Fablet.

The fixed-point SILK sources pass opus_int16/opus_int32 to CELT functions
typed for float. Example:

Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/fixed/autocorr_FIX.c:47:29:
error: incompatible pointer types passing 'const opus_int16 *' (aka 'const short *')
to parameter of type 'const opus_val16 *' (aka 'const float *')

Match Configurations/opus.xcconfig, which suppresses the warning.

* Source/ThirdParty/libwebrtc/CMakeLists.txt:

Canonical link: https://commits.webkit.org/322306@main