Wgsl misscompilation `error: no member named 'xyz' in 'PackedVec3<float>'` (320443) https://bugs.webkit.org/show_bug.cgi?id=320443 rdar://183426431
Reviewed by Tadeu Zagallo.

Indexing a packed matrix yields a packed vector, but we were
assuming it would yield an unpacked vector resulting in compilation
errors.

Test: Tools/TestWebKitAPI/Tests/WGSL/MetalCompilationTests.mm

* Source/WebGPU/WGSL/GlobalVariableRewriter.cpp:
(WGSL::RewriteGlobalVariables::getPacking):
* Tools/TestWebKitAPI/Tests/WGSL/MetalCompilationTests.mm:
(TestWGSLAPI::TEST_F(WGSLMetalCompilationTests, Packing)):

Canonical link: https://commits.webkit.org/318098@main