[WPE] GLContextEGLWPE.cpp:44:96: error: invalid cast from type ‘GLNativeWindowType {aka long long unsigned int}’ to type ‘EGLNativeWindowType {aka unsigned int} https://bugs.webkit.org/show_bug.cgi?id=179511
Reviewed by Žan Doberšek.

r217208 changed the definition of GLNativeWindowType from EGLNativeWindowType to uint64_t for platform WPE.
This built fine on a 64-bit platform since uint64_t matches the size of a pointer, but fails on 32-bits.

This switches back the definition to EGLNativeWindowType.
And we need to include <EGL/eglplatform.h> first in order to get a definition for EGLNativeWindowType itself.

This commit pretty much reverts the changes r217208 did on platform/graphics/GLContext.h

No new tests, it is a build fix.

* platform/graphics/GLContext.h:


Canonical link: https://commits.webkit.org/195920@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@225051 268f45cc-cd09-0410-ab3c-d52691b4dbfc