[Tools] `jsc-armv7-tests` EWS Fails due to syntax error in Python Script https://bugs.webkit.org/show_bug.cgi?id=297510
Reviewed by NOBODY (OOPS!).

`jsc-armv7-tests` EWS fails due to syntax error in Python Script.
builtins.TypeError: bad operand type for unary +: 'list'.

* Tools/CISupport/ews-build/steps.py:
(RunJavaScriptCoreTests.start):