[Swift in WebKit] Downlevel build failure "error: -enable-upcoming-feature IsolatedDefaultValues" https://bugs.webkit.org/show_bug.cgi?id=283219 rdar://140004811
Unreviewed build fix.

Old versions of swift are complaining about not recognizing these
compiler flags, despite AFAICT the language officially supporting the
"enable-upcoming-feature" directive.

    SwiftDriver WebKit normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'WebKit' from project 'WebKit')
    ...
    warning: Save unknown driver flag -enable-upcoming-feature as additional swift-frontend flag (in target 'WebKit' from project 'WebKit')
    error: Unexpected input file: OpenSource/Source/WebKit/IsolatedDefaultValues (in target 'WebKit' from project 'WebKit')

This isn't affecting open source builds, so maybe it's due to a slight
difference between compilers. I see that other options like this one are
passed directly to the frontend with -Xfrontend. Do that as a
speculative fix.

* Source/WebKit/Configurations/Base.xcconfig:

Canonical link: https://commits.webkit.org/286682@main