Unreviewed: dos2unix on bindings/js/JSExceptionBase.h
Visual Studio is choking on this file when generating packages for
Qt-4.8 on Windows:

"""
Source\WebCore\Bindings\js\JSExceptionBase.h:
error C4335: Mac file format detected: please convert the source file
to either DOS or UNIX format
"""

Since from all .cpp or .h files shared by all ports this is the only
one with CRLF line terminations, I'm assuming this was a mistake.

* bindings/js/JSExceptionBase.h:

Canonical link: https://commits.webkit.org/84282@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@95413 268f45cc-cd09-0410-ab3c-d52691b4dbfc