REGRESSION (r226667): CodeBlocks should be in IsoSubspaces <https://bugs.webkit.org/show_bug.cgi?id=180884>
Fixes the following build error:

    heap/Heap.cpp:2708:10: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]

* heap/Heap.cpp:
(JSC::Heap::addCoreConstraints): Remove 'this' from lambda to
fix the build.

Canonical link: https://commits.webkit.org/197322@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@226673 268f45cc-cd09-0410-ab3c-d52691b4dbfc