Fix JPEGImageDecoder boolean enum and #define TRUE/FALSE mix https://bugs.webkit.org/show_bug.cgi?id=252666
Reviewed by Michael Catanzaro.

jpeglib.h contains a typedef enum for boolean type but LCMSUniquePtr.h
include files that can contain #define TRUE/FALSE. This way build fails
with:
JPEGImageDecoder.cpp:343:43: error: invalid conversion from ‘int’ to ‘boolean’

This is because TRUE or FALSE should be an enum instead they get defined
as 1 or 0. To fix this move jpeglib.h inclusion after LCMSUniquePtr.h
inclusion. Let's also use angular paranthesis since jpeglib.h is a
system path header.

Source/WebCore/platform/image-decoders/jpeg/JPEGImageDecoder.h:

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>

Canonical link: https://commits.webkit.org/260633@main