Unreviewed, fix the internal macOS build again
Work around build failures related to API availability macros not being defined out properly in
MacCatalyst:

```
/Volumes/…/WebKit_iosmac/Source/WebKit/UIProcess/API/Cocoa/WKWebpagePreferences+Extras.swift:63:41: error: 'alternateRequest' is only available in iOS 27.0 or newer
        self.alternateRequest = wrapped.alternateRequest
```

* Source/WebKit/UIProcess/API/Cocoa/WKWebpagePreferences+Extras.swift:
* Source/WebKit/UIProcess/API/Swift/WebPage+NavigationPreferences.swift: