[Web Inspector][WinCairo] Selecting an error message in Console causes "TypeError:​ selection.focusNode.closest is not a function." https://bugs.webkit.org/show_bug.cgi?id=207248
Reviewed by Devin Rousso.

r242174 replaced Node.enclosingNodeOrSelfWithClass with
Element.closest. However, selection.focusNode isn't necessarily an
Element, but can be a Text node.

* UserInterface/Views/LogContentView.js:
(WI.LogContentView.prototype._mousemove): Use selection.focusNode.parentElement.closest
if selection.focusNode is not a instance of Element.

Canonical link: https://commits.webkit.org/220365@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@256006 268f45cc-cd09-0410-ab3c-d52691b4dbfc