[GCC] Unreviewed, build fix for Debian-12 ARM32 after 286527@main https://bugs.webkit.org/show_bug.cgi?id=270638
GCC-12 returned a build error:

error: invalid cast from type 'size_t' {aka 'unsigned int'} to type
'WebCore::TrackID'

Replace 'reinterpret_cast' for 'static_cast' since both types
are compatible.

* Source/WebCore/platform/graphics/gstreamer/mse/AppendPipeline.cpp:

Canonical link: https://commits.webkit.org/286530@main