REGRESSION(259423@main): fix VIDEO=OFF
https://bugs.webkit.org/show_bug.cgi?id=251427

Reviewed by Michael Catanzaro.

/home/thomas/buildroot/output/build/webkitgtk-2.39.6/DerivedSources/WebKit/GeneratedSerializers.cpp: In static member function ‘static void IPC::ArgumentCoder<WebCore::MediaEngineSupportParameters>::encode(IPC::Encoder&, const WebCore::MediaEngineSupportParameters&)’:
/home/thomas/buildroot/output/build/webkitgtk-2.39.6/DerivedSources/WebKit/GeneratedSerializers.cpp:17376:63: error: invalid use of incomplete type ‘const struct WebCore::MediaEngineSupportParameters’
17376 |     static_assert(std::is_same_v<std::remove_cvref_t<decltype(instance.type)>, WebCore::ContentType>);
      |                                                               ^~~~~~~~

...

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>

Canonical link: https://commits.webkit.org/259627@main