undefined reference to 'JSC::B3::BasicBlock::fallThrough() const https://bugs.webkit.org/show_bug.cgi?id=180637
Patch by Alejandro G. Castro <alex@igalia.com> on 2018-01-25
Reviewed by Michael Catanzaro.

We need to make sure the implementation of the inline functions is
compiled when we compile the code using the function, now that the
compilation is divided, or we could end up with undefined symbols
when the declaration is not inlined, at least with some compilers
and optimizations enabled -O2.

* b3/B3SwitchValue.cpp: replace the include.

Canonical link: https://commits.webkit.org/197932@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@227597 268f45cc-cd09-0410-ab3c-d52691b4dbfc