Web Inspector: exception in remote front-end load handler due to undefined reference to workerManager https://bugs.webkit.org/show_bug.cgi?id=71889
Move calls to WorkerManager load handlers into doLoadedDone method which is
called in case of remote front-end too.

Reviewed by Pavel Feldman.

* inspector/front-end/inspector.js:
(WebInspector.loaded):

Canonical link: https://commits.webkit.org/88259@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@99692 268f45cc-cd09-0410-ab3c-d52691b4dbfc