undefined reference to symbol eina_module_free https://bugs.webkit.org/show_bug.cgi?id=76681
Patch by ChangSeok Oh <shivamidow@gmail.com> on 2012-01-20
Reviewed by Martin Robinson.

eina_module_free has been used without including eina libraries after r104936.

* wtf/PlatformEfl.cmake: Add EINA_LIBRARIES.

Canonical link: https://commits.webkit.org/93535@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@105495 268f45cc-cd09-0410-ab3c-d52691b4dbfc