[WinCairo] Unreviewed build fix for WinCairo Debug builds https://bugs.webkit.org/show_bug.cgi?id=209098
It's broken since r259139 (Bug 209098).

> ..\..\Source\WebCore\platform\graphics\texmap\TextureMapperGC3DPlatformLayer.cpp(101): error C2065: 'm_state': undeclared identifier

* platform/graphics/texmap/TextureMapperGC3DPlatformLayer.cpp:
(WebCore::TextureMapperGC3DPlatformLayer::paintToTextureMapper): Replaced 'm_state' with 'm_context.m_state'.

Canonical link: https://commits.webkit.org/222629@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@259164 268f45cc-cd09-0410-ab3c-d52691b4dbfc