Cherry-pick 258892@main (ee71929690ce). https://bugs.webkit.org/show_bug.cgi?id=250573
    REGRESSION(258448@main): [GTK] Missing header with libwebrtc (USE_GSTREAMER_WEBRTC=FALSE)
    https://bugs.webkit.org/show_bug.cgi?id=250573

    Reviewed by Adrian Perez de Castro.

    When using libwebrtc (USE_GSTREAMER_WEBRTC=FALSE) since commit
    9def6e6f0258ddd9171d32bec2fffb684dbc7b8b, there's a compiler error:

    ---------
    In file included from /home/build/WebKit/Source/WebKit/UIProcess/WebPreferences.h:33,
                     from /home/build/WebKit/Source/WebKit/UIProcess/API/glib/WebKitSettingsPrivate.h:31,
                     from /home/build/WebKit/Tools/TestWebKitAPI/Tests/WebKitGLib/TestUIClient.cpp:23:
    /home/build/WebKit/WebKitBuild/Release/WebCore/PrivateHeaders/WebCore/LibWebRTCProvider.h:37:10: fatal error: webrtc/api/peer_connection_interface.h: No such file or directory
       37 | #include <webrtc/api/peer_connection_interface.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    ----------

    This adds the necessary directories search for a successful
    compilation.

    * Tools/TestWebKitAPI/glib/CMakeLists.txt:

    Canonical link: https://commits.webkit.org/258892@main