[WebCore][JS] Fix missing ENABLE(VIDEO) guard in JSResizeObserverEntryCustom
https://bugs.webkit.org/show_bug.cgi?id=324525

Reviewed by Adrian Perez de Castro.

/home/thomas/Documents/buildroot/output/build/webkitgtk-2.54.0/Source/WebCore/bindings/js/JSHTMLMediaElementCustom.cpp:35:6: error: ‘JSHTMLMediaElement’ has not been declared
   35 | void JSHTMLMediaElement::visitAdditionalChildrenInGCThread(Visitor& visitor)
      |      ^~~~~~~~~~~~~~~~~~

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>
Canonical link: https://commits.webkit.org/317695.340@webkitglib/2.54