REGRESSION(256766@main): MSVC can't compile WTFBreakpointTrapUnderConstexprContext https://bugs.webkit.org/show_bug.cgi?id=248026
Reviewed by Yusuke Suzuki.

It reports an error:

> JavaScriptCore\runtime\TypedArrayType.h(144): error C3615: constexpr function 'JSC::logElementSize' cannot result in a constant expression
> JavaScriptCore\runtime\TypedArrayType.h(166): note: failure was caused by a statement or an expression that is not valid in a constexpr context

* Source/WTF/wtf/Assertions.h:
(WTFBreakpointTrapUnderConstexprContext) Do nothing for MSVC.

Canonical link: https://commits.webkit.org/256776@main