BUILD FIX (r149410): CFRunLoopStop() doesn't know what to do with a RetainPtr<CFRunLoopRef>
Fixes the following build failure:

    WebCore/platform/cf/RunLoopCF.cpp:82:5: error: no matching function for call to 'CFRunLoopStop'
        CFRunLoopStop(m_runLoop);
        ^~~~~~~~~~~~~

* platform/cf/RunLoopCF.cpp:
(WebCore::RunLoop::stop): Call RetainPtr::get().

Canonical link: https://commits.webkit.org/133917@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@149437 268f45cc-cd09-0410-ab3c-d52691b4dbfc