REGRESSION(317420@main) PAS_ENABLE_MTE can break preprocessed distributed builds https://bugs.webkit.org/show_bug.cgi?id=319895
Reviewed by Marcus Plutowski.

Since 317420@main PAS_ENABLE_MTE can appear in contexts where the
preprocessor would output expressions like (0 && 0 && !0), which in turn
could trigger the -Wconstant-logical-operand warning. For example, in
distributed icecc builds where just the final TU is sent.

Currently, this appears in FastMalloc.cpp, with errors like:

bmalloc/Headers/bmalloc/bmalloc_heap_config.h:84:24095: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
bmalloc/Headers/bmalloc/bmalloc_heap_config.h:84:24095: note: use '&' for a bitwise operation
bmalloc/Headers/bmalloc/bmalloc_heap_config.h:84:24095: note: remove constant to silence this warning

* Source/bmalloc/libpas/src/libpas/pas_config.h: Ensure PAS_ENABLE_MTE
  resolves to a constant instead of an expression.

Canonical link: https://commits.webkit.org/317638@main