Web Inspector: TypeError:​ sourceCodeLocation.populateLiveDisplayLocationTooltip is not a function https://bugs.webkit.org/show_bug.cgi?id=171259
Patch by Fujii Hironori <Hironori.Fujii@sony.com> on 2017-04-25
Reviewed by Joseph Pecoraro.

The first argument of WebInspector.createSourceCodeLocationLink
should be SourceCodeLocation type.

* UserInterface/Views/TimelineDataGridNode.js:
(WebInspector.TimelineDataGridNode.prototype.createCellContent):
Pass 'callFrame.sourceCodeLocation' instead of 'value' to the
first argument.

Canonical link: https://commits.webkit.org/188152@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@215749 268f45cc-cd09-0410-ab3c-d52691b4dbfc